### ISSUE TITLE
RubyNLP

### ISSUE THREAD

**Issue by arbox** [blackwinter/hal4r#1]
Dear Jens ,

we've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository. Of course you are welcome to add topics to all other nlp related repositories and to contribute to our RubyNLP and RubyML lists.

Thank you for the project!

**Comment by blackwinter** [comment]
Thanks, Andrei! I've added the [`rubynlp`](/search?q=topic%3Arubynlp+user%3Ablackwinter&type=Repositories) topic to the repositories that I think might fit. I'm no longer active in this area, though, and the projects aren't actively developed.

**Comment by arbox** [comment]
We have to thank you!
Not actively developed doesn't mean useless. And a visible project may attract contributors or collaborators.

**Comment by blackwinter** [comment]
Exactly! And I appreciate that your RubyNLP initiative could provide wider exposure :)
